filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/containers/storage/overlay-containers/*/*.log"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata:
      host: "unix:///run/podman/podman.sock"

output.logstash:
  hosts: ["elk_host:5044"]

# Add these lines for better monitoring
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
