filebeat:
  image: docker.elastic.co/beats/filebeat:8.12.0
  user: root
  volumes:
    - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  command: [ "--strict.perms=false" ]
  depends_on:
    - elasticsearch
    - logstash
  environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - KIBANA_HOST=http://kibana:5601
  restart: unless-stopped
  # ⭐️ DEFINE ELK HOST HERE (remote hosts)
  extra_hosts:
    - "elk_host:dankserver"
  network_mode: "host"
